apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: APPNAME
  namespace: scratch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
      - name: APPNAME
        image: gurvin/minimal-notebook
        resources:
          requests:
            cpu: 200m
            memory: 200M
          limits:
            cpu: 400m
            memory: 400M
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: APPNAME
  namespace: scratch
spec:
  ports:
  - port: 8888
    name: http
  selector:
    app: APPNAME

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: APPNAME
  namespace: scratch
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - APPNAME.scratch.nirdtest.uninett.no
    secretName: APPNAME-tls
  rules:
  - host: APPNAME.scratch.nirdtest.uninett.no
    http:
      paths:
      - path: /
        backend:
          serviceName: APPNAME
          servicePort: 8888

---

apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: APPNAME
  namespace: scratch
spec:
  podSelector:
    matchLabels:
      app: APPNAME
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-ingress
      ports:
        - protocol: tcp
          port: 8888
